sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dantedxwolf -f Dockerfile.dev .

script:
  - docker run -e CI=true dantedxwolf
deploy:
  provider: heroku
  api_key: "61bc162f-06c5-42e3-a592-93cfd49398c1"
  app: "showwcaseapp"